//
// Created by user on 2021/11/28.
//

#ifndef MULTITHREADEDFILEOPERATE_LITE_DEFS_H
#define MULTITHREADEDFILEOPERATE_LITE_DEFS_H

#include <assert.h>

#define PENDING_BYTE 0x10000000
#define RESERVED_BYTE (PENDING_BYTE + 1)
#define SHARED_BYTE (PENDING_BYTE + 2)

#define MAX_NAME_LENGTH 1024
#define LITE_MIN_FD 3

#define LITE_SUCCESS 0
#define LITE_NO_MEM 1
#define LITE_ERROR_LOCK 2
#define LITE_BUSY  3
#define LITE_NAME_TOO_LONG 4
#define LITE_ERROR_OPEN 5

#define NONE_LOCK 0
#define SHARED_LOCK 1
#define RESERVED_LOCK 2
#define PENDING_LOCK 3
#define EXCLUSIVE_LOCK 4

#endif //MULTITHREADEDFILEOPERATE_LITE_DEFS_H
